# Generated by Django 4.2.2 on 2023-06-21 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_tag_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="uuid",
        ),
    ]
